<a href="https://colab.research.google.com/github/oven8/Computational-Physics-2024/blob/main/Assgn1_Jahaan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.linalg import lu
import time

# Problem 11


In [ ]:
A1 = np.array([[3,-1,1], [3,6,2],[3,3,7]]).astype(float)
b1 = np.array([1,0,4]).astype(float)
A2 = np.array([[10,-1,0], [-1,10,-2],[0,-2,10]]).astype(float)
b2 = np.array([9,7,6]).astype(float)
A3 = np.array([[10,5,0,0], [5,10,-4,0],[0,-2,8,-1],[0,0,-1,5]]).astype(float)
b3 = np.array([6,25,-11,-11]).astype(float)
A4 = np.array([[4,1,1,0,1],[-1,-3,1,1,0],[2,1,5,-1,-1],[-1,-1,-1,4,0],[0,2,-1,1,4]]).astype(float)
b4 = np.array([6,6,6,6,6]).astype(float)
x1 = np.linalg.solve(A1, b1)
x2 = np.linalg.solve(A2, b2)
x3 = np.linalg.solve(A3, b3)
x4 = np.linalg.solve(A4, b4)

print("Solution for the first system:",x1)
print("Solution for the second system:",x2)
print("Solution for the third system:",x3)
print("Solution for the fourth system:",x4)

Solution for the first system: [ 0.03508772 -0.23684211  0.65789474]
Solution for the second system: [0.99578947 0.95789474 0.79157895]
Solution for the third system: [-0.57623762  2.35247525 -1.08910891 -2.41782178]
Solution for the fourth system: [ 0.78663239 -1.00257069  1.86632391  1.9125964   1.98971722]


# Problem 16

In [ ]:
A=np.array([[0.2,0.1,1,1,0],[0.1,4,-1,1,-1],[1,-1,60,0,-2],[1,1,0,8,4],[0,-1,-2,4,700]]).astype(float)
b=np.array([1,2,3,4,5]).astype(float)
x0=np.array([0,0,0,0,0]).astype(float)
xt = np.array([7.859713071, 0.422926408, -0.073592239, -0.540643016, 0.010626163])

In [ ]:
# Jacobi method
def gauss_jacobi(A, b, x0, tol=0.01, max_iter=100):
    n = len(A)
    U = -np.triu(A,k=1)
    L = -np.tril(A,k=-1)
    D = A + U + L
    T = np.matmul(np.linalg.inv(D),np.add(L,U))
    C = np.matmul(np.linalg.inv(D),b)
    x = np.copy(x0)
    for k in range(max_iter):
        x_old = np.copy(x)
        x = np.add(np.matmul(T,x),C)
        if np.linalg.norm(x - xt) < tol:
            return x,k+1
    raise ValueError("Gauss-Jacobi method did not converge")

solution = gauss_jacobi(A, b, x0)
print("Solution:", solution[0])
print("Number of iterations:", solution[1])

Solution: [ 7.86798447  0.4239069  -0.0731638  -0.5370925   0.01063184]
Iterations: 39


In [ ]:
# Gauss-Seidel method
def gauss_siedel(A, b, x0, tol=0.01, max_iter=1000):
    n = len(A)
    U = -np.triu(A,k=1)
    L = -np.tril(A,k=-1)
    D = A + U + L
    T = np.matmul(np.linalg.inv(np.add(D,-L)),U)
    C = np.matmul(np.linalg.inv(np.add(D,-L)),b)
    x = np.copy(x0)
    for k in range(max_iter):
        x_old = np.copy(x)
        x = np.add(np.matmul(T,x),C)
        if np.linalg.norm(x - xt) < tol:
            return x,k+1
    raise ValueError("Gauss-Seidel method did not converge")

solution = gauss_siedel(A, b, x0)
print("Solution:", solution[0])
print("Number of iterations:", solution[1])

Solution: [ 7.85091478  0.42280131 -0.07344797 -0.53952326  0.01062   ]
Iterations: 18


In [ ]:
# Relaxation method
def relaxation_method(A, b, x0, tol=0.01, max_iter=1000, omega=1.25):
    n = len(b)
    x = np.copy(x0)
    for k in range(max_iter):
        x_old = np.copy(x)
        for i in range(n):
            sum = 0
            for j in range(n):
                if j != i:
                    sum += A[i][j] * x[j]
            x[i] = (1 - omega) * x_old[i] + (omega / A[i][i]) * (b[i] - sum)
        r = np.multiply(np.diag(A),np.add(x,-x_old))
        if np.linalg.norm(x - xt) < tol:
            return x,k+1
    raise ValueError("Relaxation method did not converge")

solution = relaxation_method(A, b, x0)
print("Solution:", solution[0])
print("Number of iterations:", solution[1])

Solution: [ 7.85152701  0.42277371 -0.07348303 -0.53978369  0.01062286]
Iterations: 7


In [ ]:
# Conjugate Gradient method
def conjugate_gradient(A, b, x0, tol=0.01, max_iter=1000):
    r = b - np.dot(A, x0)
    p = np.copy(r)
    x = np.copy(x0)
    rsold = np.dot(r, r)
    for k in range(max_iter):
        Ap = np.dot(A, p)
        alpha = rsold / np.dot(p, Ap)
        x = x + alpha * p
        if np.linalg.norm(x - xt) < tol:
            return x,k+1
        r = r - alpha * Ap
        rsnew = np.dot(r, r)
        beta = (rsnew / rsold)
        p = r + beta * p
        rsold = np.copy(rsnew)
    raise ValueError("Relaxation method did not converge")

solution = conjugate_gradient(A, b, x0)
print("Solution:", solution[0])
print("Number of iterations:", solution[1])


Solution: [ 7.85971308  0.42292641 -0.07359224 -0.54064302  0.01062616]
Number of iterations: 5


# Problem 17

In [ ]:
def qr_eigenvalues(A, max_iter=100, tol=1e-6):
    n = A.shape[0]
    V = np.eye(n)

    for _ in range(max_iter):
        Q, R = np.linalg.qr(A)
        A = np.dot(R, Q)
        V = np.dot(V, Q)
        if np.abs(A.diagonal(-1)).max() < tol:
            break

    eigenvalues = A.diagonal()
    return eigenvalues, V


A=np.array([[5,-2],[-2,8]])
eigenvalues, eigenvectors = qr_eigenvalues(A)
print("Eigenvalues using QR decomposition:",eigenvalues)
eigenvalues1, eigenvectors1=np.linalg.eigh(A)
print("Eigenvalues using numpy.linalg.eigh:",eigenvalues1)

Eigenvalues using QR decomposition: [9. 4.]
Eigenvalues using numpy.linalg.eigh: [4. 9.]


# Problem 18

In [ ]:
import numpy as np

def power_method(A, max_iter=1000, tol=0.01):
    n = A.shape[0]
    x = np.random.rand(n)
    x /= np.linalg.norm(x)
    ev0 = 0

    for k in range(max_iter):
        x_new = np.matmul(A, x)
        ev = np.dot(x_new, x)
        x_new /= np.linalg.norm(x_new)

        if abs(ev0 - ev)/ev < tol:
            break

        x = x_new
        ev0 = ev

    return ev

# Example matrix
A = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])

# Apply Power Method to find dominant eigenvalue and eigenvector
eigenvalue = power_method(A)

print("Dominant eigenvalue:", eigenvalue)


Dominant eigenvalue: 3.397359402160364


# Problem 19

In [2]:
def sigma(sv, m, n):
    Sigma = np.zeros((m, n))

    min_dim = min(m, n)
    Sigma[:min_dim, :min_dim] = np.diag(sv)

    return Sigma

In [6]:
st = time.time()
A1=np.array([[2,1],[1,0]])
U1,S1,V1=np.linalg.svd(A1)

Sigma1 = sigma(S1,U1.shape[1],V1.shape[1])

D1=np.dot(np.dot(U1,Sigma1),V1)

et = time.time()
print("Matrix(U):",U1)

print("Matrix(S):",Sigma1)

print("Matrix(V):",V1)

print("Matrix Product(USV):",D1)

print("Time for computation",et-st)

Matrix(U): [[-0.92387953 -0.38268343]
 [-0.38268343  0.92387953]]
Matrix(S): [[2.41421356 0.        ]
 [0.         0.41421356]]
Matrix(V): [[-0.92387953 -0.38268343]
 [ 0.38268343 -0.92387953]]
Matrix Product(USV): [[ 2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -3.81016887e-17]]
Time for computation 0.0006134510040283203


In [8]:
st = time.time()
A2=np.array([[2,1],[1,0],[0,1]])
U2,S2,V2=np.linalg.svd(A2)

Sigma2 = sigma(S2,U2.shape[1],V2.shape[1])

D2=np.dot(np.dot(U2,Sigma2),V2)

et = time.time()
print("Matrix(U):",U2)

print("Matrix(S):",Sigma2)

print("Matrix(V):",V2)

print("Matrix Product(USV):",D2)

print("Time for computation",et-st)

Matrix(U): [[-9.12870929e-01  4.80183453e-17 -4.08248290e-01]
 [-3.65148372e-01 -4.47213595e-01  8.16496581e-01]
 [-1.82574186e-01  8.94427191e-01  4.08248290e-01]]
Matrix(S): [[2.44948974 0.        ]
 [0.         1.        ]
 [0.         0.        ]]
Matrix(V): [[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]
Matrix Product(USV): [[ 2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -6.81060746e-17]
 [-1.23617226e-16  1.00000000e+00]]
Time for computation 0.0006489753723144531


In [9]:
st = time.time()
A3=np.array([[2,1],[-1,1],[1,1],[2,-1]])
U3,S3,V3=np.linalg.svd(A3)

Sigma3 = sigma(S3,U3.shape[1],V3.shape[1])

D3=np.dot(np.dot(U3,Sigma3),V3)

et = time.time()
print("Matrix(U):",U3)

print("Matrix(S):",Sigma3)

print("Matrix(V):",V3)

print("Matrix Product(USV):",D3)

print("Time for computation",et-st)

Matrix(U): [[-0.63245553 -0.5        -0.52229321 -0.27786652]
 [ 0.31622777 -0.5        -0.30196857  0.74753928]
 [-0.31622777 -0.5         0.79704714  0.12130893]
 [-0.63245553  0.5        -0.02721464  0.59098169]]
Matrix(S): [[3.16227766 0.        ]
 [0.         2.        ]
 [0.         0.        ]
 [0.         0.        ]]
Matrix(V): [[-1. -0.]
 [-0. -1.]]
Matrix Product(USV): [[ 2.  1.]
 [-1.  1.]
 [ 1.  1.]
 [ 2. -1.]]
Time for computation 0.0007576942443847656


In [10]:
st = time.time()
A4=np.array([[1,1,0],[-1,0,1],[0,1,-1],[1,1,-1]])
U4,S4,V4=np.linalg.svd(A4)

Sigma4 = sigma(S4,U4.shape[1],V4.shape[1])

D4=np.dot(np.dot(U4,Sigma4),V4)

et = time.time()
print("Matrix(U):",U4)

print("Matrix(S):",Sigma4)

print("Matrix(V):",V4)

print("Matrix Product(USV):",D4)

print("Time for computation",et-st)

Matrix(U): [[-4.36435780e-01  7.07106781e-01  4.08248290e-01 -3.77964473e-01]
 [ 4.36435780e-01  7.07106781e-01 -4.08248290e-01  3.77964473e-01]
 [-4.36435780e-01  3.33066907e-16 -8.16496581e-01 -3.77964473e-01]
 [-6.54653671e-01  3.33066907e-16 -5.55111512e-17  7.55928946e-01]]
Matrix(S): [[2.64575131 0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]
 [0.         0.         0.        ]]
Matrix(V): [[-0.57735027 -0.57735027  0.57735027]
 [ 0.          0.70710678  0.70710678]
 [ 0.81649658 -0.40824829  0.40824829]]
Matrix Product(USV): [[ 1.00000000e+00  1.00000000e+00  2.52368982e-17]
 [-1.00000000e+00  1.27610516e-17  1.00000000e+00]
 [-8.05746207e-17  1.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -1.00000000e+00]]
Time for computation 0.0009691715240478516


In [11]:
st = time.time()
A5=np.array([[0,1,1],[0,1,0],[1,1,0],[0,1,0],[1,0,1]])
U5,S5,V5=np.linalg.svd(A5)

Sigma5 = sigma(S5,U5.shape[1],V5.shape[1])

D5=np.dot(np.dot(U5,Sigma5),V5)

et = time.time()
print("Matrix(U):",U5)

print("Matrix(S):",Sigma5)

print("Matrix(V):",V5)

print("Matrix Product(USV):",D5)

print("Time for computation",et-st)

Matrix(U): [[-5.47722558e-01  3.50476164e-16  7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01  4.08248290e-01 -1.48383873e-16 -5.43516408e-01
   6.36073827e-01]
 [-5.47722558e-01 -7.02388902e-17 -7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01  4.08248290e-01 -1.71841615e-16  8.07633333e-01
   2.18468301e-01]
 [-3.65148372e-01 -8.16496581e-01  2.43277252e-16  1.32058463e-01
   4.27271064e-01]]
Matrix(S): [[2.23606798 0.         0.        ]
 [0.         1.41421356 0.        ]
 [0.         0.         1.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
Matrix(V): [[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-5.77350269e-01  5.77350269e-01 -5.77350269e-01]
 [-7.07106781e-01 -3.88578059e-16  7.07106781e-01]]
Matrix Product(USV): [[-1.88904597e-16  1.00000000e+00  1.00000000e+00]
 [-7.58392910e-17  1.00000000e+00 -7.62142974e-17]
 [ 1.00000000e+00  1.00000000e+00 -3.49858899e-16]
 [-1.23350918e-16  1.00000000e+0